### ISSUE TITLE
app.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [madmurdok/an-study-shop#3]
Тут можно не использоват второй параметр
@ViewChild('appTitle', {read: ViewContainerRef}) appTitle: ViewContainerRef;

тогда эта строчка будет this.appTitle.nativeElement.innerText = 'Welcome to Tea Shop!';
ну а делать это нужно в другом хуке, не в ngOnInit, а в ngAfterViewInit

**Comment by madmurdok** [comment]
Поправлено в Task3
